language: node_js

node_js:
  - '10.0.0'
cache:
  npm: false
script:
  - npm run build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: development
