language: node_js

node_js:
  - '11.0.0'
cache: npm
script:
  - npm run build
before_install:
  - npm i -g npm@6.14.8
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: development
